services:
  pg-bench:
    image: postgres:15
    container_name: pg-bench
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql-bench:
    image: mysql:8.4
    container_name: mysql-bench
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  app:
    build: .
    container_name: sql-benchmark-suite
    depends_on:
      - pg-bench
      - mysql-bench
    environment:
      # POSTGRES
      POSTGRES_HOST: pg-bench
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}

      # MYSQL
      MYSQL_HOST: mysql-bench
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT}

    volumes:              
      - ./src/benchmark/results:/app/src/benchmark/results

volumes:
  pgdata:
  mysqldata:
